// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2QBusS49BwYWxmzCjnMOsWA_AjZCd8A',
    appId: '1:456307585043:web:323a9b0797d2c8c437cfe6',
    messagingSenderId: '456307585043',
    projectId: 'smartmoney-fef2d',
    authDomain: 'smartmoney-fef2d.firebaseapp.com',
    storageBucket: 'smartmoney-fef2d.appspot.com',
    measurementId: 'G-5HWSJ71YLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTFFBtcCk6m7Ph9cBHLwCg_TUBsAJNyTY',
    appId: '1:456307585043:android:d3ee351edcc1502137cfe6',
    messagingSenderId: '456307585043',
    projectId: 'smartmoney-fef2d',
    storageBucket: 'smartmoney-fef2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZo7Swy6AlqaK3UwErbjOEwOey_SiRSHc',
    appId: '1:456307585043:ios:0afc66de9cdb339f37cfe6',
    messagingSenderId: '456307585043',
    projectId: 'smartmoney-fef2d',
    storageBucket: 'smartmoney-fef2d.appspot.com',
    androidClientId:
        '456307585043-p9tppligjrc7pku3fomislrh2jsgf6l7.apps.googleusercontent.com',
    iosClientId:
        '456307585043-g19p445eg9dvhohmqm4ru6gjft4h1gk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMoneyTrading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZo7Swy6AlqaK3UwErbjOEwOey_SiRSHc',
    appId: '1:456307585043:ios:0afc66de9cdb339f37cfe6',
    messagingSenderId: '456307585043',
    projectId: 'smartmoney-fef2d',
    storageBucket: 'smartmoney-fef2d.appspot.com',
    androidClientId:
        '456307585043-p9tppligjrc7pku3fomislrh2jsgf6l7.apps.googleusercontent.com',
    iosClientId:
        '456307585043-g19p445eg9dvhohmqm4ru6gjft4h1gk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMoneyTrading',
  );
}
